#ifndef SETW_CONSTS_H
#define SETW_CONSTS_H

const int WINDOW_OUTER = 80;
const int WINDOW_INNER = 78;

const int MENU_HEAD_PADDING = 28;
const int MENU_SUBHEAD_PADDING = 31;
const int MENU_BODY_PADDING = 24;

const int BOOK_INFO_TITLE_PADDING = 28;
const int BOOK_INFO_SUBTITLE_PADDING = 35;
const int BOOK_INFO_BODY_PADDING = 38;

const int BOOK_EDITOR_TITLE_PADDING = 53;
const int BOOK_EDITOR_SUBTITLE_PADDING = 45;
const int BOOK_EDITOR_BODY_PADDING = BOOK_INFO_BODY_PADDING;

const int DB_SIZE_PADDING = 4;
const int BOOK_COUNT_PADDING = 20;

const int PENDING_VALUES_PADDING = 70;

const int BOOK_INFO_TITLE_WIDTH = WINDOW_INNER - BOOK_INFO_TITLE_PADDING;
const int BOOK_INFO_SUBTITLE_WIDTH = WINDOW_INNER - BOOK_INFO_SUBTITLE_PADDING;
const int BOOK_INFO_BODY_WIDTH = WINDOW_INNER - BOOK_INFO_BODY_PADDING;

const int MENU_HEAD_WIDTH = WINDOW_INNER - MENU_HEAD_PADDING;
const int MENU_SUBHEAD_WIDTH = WINDOW_INNER - MENU_SUBHEAD_PADDING;
const int MENU_BODY_WIDTH = WINDOW_INNER - MENU_BODY_PADDING;

const int BOOK_EDITOR_TITLE_WIDTH = WINDOW_INNER - BOOK_EDITOR_TITLE_PADDING;
const int BOOK_EDITOR_SUBTITLE_WIDTH = WINDOW_INNER - BOOK_EDITOR_SUBTITLE_PADDING;
const int BOOK_EDITOR_BODY_WIDTH = WINDOW_INNER - BOOK_EDITOR_BODY_PADDING - 6;

const int PENDING_VALUES_WIDTH = WINDOW_INNER - PENDING_VALUES_PADDING;


#endif // SETW_CONSTS_H