#ifndef SETW_CONSTS_H
#define SETW_CONSTS_H

const int WINDOW_WIDTH = 78;
const int TITLE_PADDING = 28;
const int SUBTITLE_PADDING = 35;
const int BODY_PADDING = 38;

const int TITLE_WIDTH = WINDOW_WIDTH - TITLE_PADDING;
const int SUBTITLE_WIDTH = WINDOW_WIDTH - SUBTITLE_PADDING;
const int BODY_WIDTH = WINDOW_WIDTH - BODY_PADDING;


#endif // SETW_CONSTS_H