var files_dup =
[
    [ "addBook.cpp", "addBook_8cpp.html", "addBook_8cpp" ],
    [ "addBook.h", "addBook_8h.html", "addBook_8h" ],
    [ "book_info_deref.cpp", "book__info__deref_8cpp.html", "book__info__deref_8cpp" ],
    [ "book_info_deref.h", "book__info__deref_8h.html", "book__info__deref_8h" ],
    [ "bookinfo.cpp", "bookinfo_8cpp.html", "bookinfo_8cpp" ],
    [ "bookType.cpp", "bookType_8cpp.html", null ],
    [ "bookType.h", "bookType_8h.html", "bookType_8h" ],
    [ "cashier.cpp", "cashier_8cpp.html", "cashier_8cpp" ],
    [ "cashier.h", "cashier_8h.html", "cashier_8h" ],
    [ "deleteBook.cpp", "deleteBook_8cpp.html", "deleteBook_8cpp" ],
    [ "deleteBook.h", "deleteBook_8h.html", "deleteBook_8h" ],
    [ "editBook.cpp", "editBook_8cpp.html", "editBook_8cpp" ],
    [ "editBook.h", "editBook_8h.html", "editBook_8h" ],
    [ "int_input_checked.cpp", "int__input__checked_8cpp.html", "int__input__checked_8cpp" ],
    [ "int_input_checked.h", "int__input__checked_8h.html", "int__input__checked_8h" ],
    [ "invmenu.cpp", "invmenu_8cpp.html", "invmenu_8cpp" ],
    [ "invmenu.h", "invmenu_8h.html", "invmenu_8h" ],
    [ "linkedlist.h", "linkedlist_8h.html", "linkedlist_8h" ],
    [ "lookUpBook.cpp", "lookUpBook_8cpp.html", "lookUpBook_8cpp" ],
    [ "lookUpBook.h", "lookUpBook_8h.html", "lookUpBook_8h" ],
    [ "mainmenu.cpp", "mainmenu_8cpp.html", "mainmenu_8cpp" ],
    [ "orderedLinkedList.h", "orderedLinkedList_8h.html", "orderedLinkedList_8h" ],
    [ "reports.cpp", "reports_8cpp.html", "reports_8cpp" ],
    [ "reports.h", "reports_8h.html", "reports_8h" ],
    [ "selsort.h", "selsort_8h.html", "selsort_8h" ],
    [ "setw_consts.h", "setw__consts_8h.html", "setw__consts_8h" ],
    [ "unorderedLinkedList.h", "unorderedLinkedList_8h.html", "unorderedLinkedList_8h" ]
];